---
name: "Question Request"
description: "Submit a question request for guidance on using the application."
title: "[Question] "
labels:
  - question
  - help
body:
  - type: dropdown
    id: application_id
    attributes:
      label: "Application ID"
      description: "Enter the APEX Application where the issue occurred."
      options:
        - security-tool
        - ext-integration
    validations:
      required: true
    
  - type: input
    id: application_page
    attributes:
      label: "Application Page"
      description: "Enter the APEX page number where the issue occurred."
      placeholder: "e.g., 12 or '/custom-roles'"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "----"

  - type: textarea
    id: question_summary
    attributes:
      label: "Question Summary"
      description: "Describe your question or the guidance you need in detail."
      placeholder: "Provide all relevant details about your question."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Provide any context or background information that might help in answering your question."
      placeholder: "Include any relevant details or scenarios."
    validations:
      required: false

  - type: input
    id: related_features
    attributes:
      label: "Related Features"
      description: "Mention any related features or components relevant to your question."
      placeholder: "e.g., API, User Interface"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "----"

  - type: markdown
    attributes:
      value: "### Environment Details"

  - type: input
    id: apex_version
    attributes:
      label: "APEX Version"
      description: "Provide the version of Oracle APEX."
      placeholder: "e.g., 23.0.1"
    validations:
      required: false

  - type: input
    id: database_version
    attributes:
      label: "Database Version"
      description: "Provide the version of Oracle Database."
      placeholder: "e.g., 23ai"
    validations:
      required: false

  - type: input
    id: application_version
    attributes:
      label: "APEX Application Version"
      description: "Provide the version of the APEX Application."
      placeholder: "e.g., v2.0.0.1"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "----"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Provide any other information that might be useful."
      placeholder: "Any other details, screenshots, or examples."
    validations:
      required: false

---
